# Generated by Django 4.1.4 on 2023-10-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'verbose_name_plural': 'All Clothes'},
        ),
    ]
