# Generated by Django 4.1.4 on 2023-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_cloth_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='keywords',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
