# Generated by Django 4.1.4 on 2023-10-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_cloth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frequency_in_a_month',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
